### ISSUE TITLE
Kludge: revert dev spaces static deployment image

### ISSUE THREAD

**Issue by codekow** [redhat-na-ssa/demo-ai-gitops-catalog#40]
See https://github.com/eclipse-che/che-dashboard/pull/990

```
spec:
  components:
    dashboard:
      deployment:
        containers:
          - image: quay.io/eclipse/che-dashboard:pr-990
```

Need to undo the kludge
[here](https://github.com/codekow/demo-ai-gitops-catalog/blob/main/components/operators/devspaces/instance/base/checluster.yaml)
